version: '3.7'
services:
  db:
    container_name: 'tvshows_db'
    image: 'mongo:4.0.10'
    restart: unless-stopped
    command:
      - '--dbpath'
      - '/data/db'
    ports:
      - '27017:27017'
    volumes:
      - '${PWD}/mongo_data/db:/data/db'
    networks:
      mynet:
        aliases:
          - 'tvmazedb'

  api:
    build:
      context: './'
      dockerfile: './src/Host/Dockerfile'
    image: 'tvshows_api:latest'
    container_name: 'tvshows_api'
    ports:
      - '5080:80'
    depends_on:
      - db
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
